name:  build

on: [ push, delete, create ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.x
      - name: Install and Build
        run: |
          npm install --legacy-peer-deps
          npm run build
